In [ ]:
#Como cargar un dataframe partiendo de un fichero .csv
import pandas as pd
#Cargar un fichero csv, dentro del parentesis va la ruta del fichero
#En windows los slashs \ 1 solo no funciona.
#3 opciones para solucionarlo, primero poner doble barra \\
#con el slash al reves /
#con una r delante, raw wn crudo
january_2019 = pd.read_csv(r"C:\Users\formacio\Downloads\January 2019 (1).csv")
february_2019 = pd.read_csv(r"C:\Users\formacio\Downloads\February 2019 (1).csv")

In [ ]:
#Tengo el dataframe de january_2019 + el de february_2019
#consolidar los dataframes en un solo dataframe para poder tener totales
#warning los conjuntos de datos tienen que tener la misma estructura
january_2019.info()
print()
february_2019.info()

In [ ]:
#Vamos a concatenar los 2 dataframes y reindexar altamente recomendado
dos_meses = pd.concat([january_2019,february_2019],ignore_index=True)
dos_meses

In [ ]:
#Como eliminar una columna, primero la tengo que crear
dos_meses['a_eliminar'] = "A Eliminar"
dos_meses

In [ ]:
#Eliminar un columna, mediante reasignación
dos_meses = dos_meses.drop(['a_eliminar'],axis=1)
dos_meses

In [ ]:
#Modificar un dataframe sin reasignar con inplace (En su lugar)
dos_meses.drop(['a_eliminar'],axis=1,inplace=True)
dos_meses

Eliminar varias columnas a la vez
dos_meses.drop(['Campo1','Campo2],axis=1,inplace=True)
dos_meses.dropna(axis=1) Si una columna tiene todas sus filas vacias la elimina
dos_mese.dropna(axis=0) Si una fila tiene todas sus columnas vacias las elimina - eliminar filas en blanco

In [ ]:
#Ordenar un dataframe por un campo concreto
dos_meses.sort_values(ascending=True, by='Customer')

In [ ]:
#Ordenar un dataframe por mas de un campo concreto
dos_meses.sort_values(ascending=True, by=['Customer','Revenue'])

In [ ]:
#Filtrar + ordenar un dataframe, todo en la misma linea
dos_meses[dos_meses['Units']>100].sort_values(ascending=True, by='Units')

Practica 27: Consolidar en un solo dataframe, los ficheros csv (january + February + March 2019), queremos ver en un texto la suma total de Units, siempre que units sea mayor de 160

Practica 28: Con el Dataframe de los 3 meses, ver solo las columnas Customer, Country y Revenue, de los 30 primreos registros ordenados por Country

In [ ]:
#Solución practica 27
#0.- llamar a la libreria
import pandas as pd
#1.- cargar el dataframe de january
january_2019 = pd.read_csv(r"C:\Users\formacio\Downloads\January 2019 (1).csv")
#2.- cargar el dataframe de february
february_2019 = pd.read_csv(r"C:\Users\formacio\Downloads\February 2019 (1).csv")
#3.- cargar el dataframe de march
march_2019 = pd.read_csv(r"C:\Users\formacio\Downloads\March 2019 (1).csv")
#4.- conacatenar los 3 dataframes
primer_tri_2019 = pd.concat([january_2019,february_2019,march_2019],ignore_index=True)
#5.- comprobar si se lee bien el dataframe resultante
print(primer_tri_2019) 
#6.- calcular el resultado modo A
resultado = primer_tri_2019[primer_tri_2019['Units']>160].Units.sum()
#7.- calcular el resultado modo B
resultado = primer_tri_2019[primer_tri_2019['Units']>160]['Units'].sum()
#8.- mostrar el resultado
print("La suma de unidades que son mayores de 160 son",resultado)

In [ ]:
#Solución de la practica 28, voy hacerlo en una sola linea
primer_tri_2019[['Country','Revenue','Customer']].head(30).sort_values(ascending=True,by='Country', ignore_index=True)

In [ ]:
#Como averiguar si las columnas son iguales o diferentes
january_2019 = pd.read_csv(r"C:\Users\formacio\Downloads\January 2019 (1).csv")
february_2019 = pd.read_csv(r"C:\Users\formacio\Downloads\February 2019 (1).csv")

#Igualar los nombres
january_2019.columns = february_2019.columns

#Averiguar las columnas de january que no estan en february
print("Solo January",january_2019.columns.difference(february_2019))
#Al reves
print("Solo February",february_2019.columns.difference(january_2019))

In [ ]:
#Con la comparativa, puedo averiguar si son iguales o no
son_iguales = set(january_2019) == set(february_2019)
print(son_iguales)

In [ ]:
#Los accesores de pandas, un accesor es una colección de metodos agrupados de una clase, que se llama mediante la anotación de un punto, str=string, dt=datetime
primer_tri_2019['Country'].str.upper()

In [ ]:
#Cuidado antes de usar el accesor dt, me tengo que asegurar que el campo es datetime, puede que no este ajustado el tipo de campo (si el valor es susceptible de ser una fecha), la tengo que convertir
#Como convertir un campo a fecha
primer_tri_2019['Date'] = pd.to_datetime(primer_tri_2019['Date'])
#No existe la conversion a date, siempre es datetime (llevara las horas)
#tengo que ajustar el date, despues del accesor dt
#primer_tri_2019['Date'] = primer_tri_2019['Date'].dt.date
#Como usar el accesor dt
print(primer_tri_2019['Date'].dt.strftime('%d/%m/%Y'))

Practica 29: Obtener un dataframe que consolide los datos de February + March 2019.csv. Crear una columna que me de 15 dias menos que la fecha Date y me la muestre en el formato dd-mm-yyyy, crear otra columna que nos ponga el mes de la columna Date en castellano.

In [ ]:
#Solución practica 29
#0.- Cargar las librerias
import pandas as pd
import locale
from datetime import timedelta as tiempo
#1.- Cargar February + March por individual
february_2019 = pd.read_csv(r"C:\Users\formacio\Downloads\February 2019 (1).csv")
march_2019 = pd.read_csv(r"C:\Users\formacio\Downloads\March 2019 (1).csv")
#2.- Concatenar los 2 dataframes
feb_mar = pd.concat([february_2019,march_2019],ignore_index=True)
#3.- Ver la info del df resultante
#feb_mar.info()
#4.- Voy a convertir el campo Date en datetime
feb_mar['Date'] = pd.to_datetime(feb_mar['Date'])
#5.- Voy a justar el locale para el idioma
locale.setlocale(locale.LC_TIME, 'es_ES.UTF-8')
#6.- Voy a decrementar 15 dias a la fecha en una nueva columna
feb_mar['Date_15'] = feb_mar['Date'] + tiempo(days=-15)
feb_mar['Date_15'] = feb_mar['Date_15'].dt.strftime('%d/%m/%Y')
#7.- Poner en una nueva columna el mes en letras en mayus
feb_mar['Mes'] = feb_mar['Date'].dt.strftime('%B').str.upper()
feb_mar

In [ ]:
#Mediante el accesor str, llamo a un metodo de la clase str
primer_tri_2019['Country'].str.lower()

In [ ]:
#Ver los registros cuyo CUSTOMER contiene la palabra Industries
filtro = primer_tri_2019['Customer'].str.contains('Industries')
primer_tri_2019[filtro]

In [ ]:
#Ver los clientes cuyo nombre, empieza por la letra C
filtro = primer_tri_2019['Customer'].str.startswith('C')
primer_tri_2019[filtro]['Customer']

In [ ]:
#Ver los clientes cuyo nombre, termina con la letra s
filtro = primer_tri_2019['Customer'].str.endswith('s')
primer_tri_2019[filtro]['Customer']

In [ ]:
#Ver los registros cuya columna Country este dentro de una lista con isin
filtro = primer_tri_2019['Country'].isin(['Colombia','USA'])
primer_tri_2019[filtro]

In [ ]:
#Ver los registros cuya columna Country no este dentro de una lista, es lo contrario de isin, lo contrario seria con el caracter virgulilla delante ~ como se escriba la virgulilla con alt + 126 del teclado numerico o con AltGr + 4 de arriba + apretar tecla espacio
filtro = ~primer_tri_2019['Country'].isin(['Colombia','USA'])
primer_tri_2019[filtro]

In [ ]:
#Como ver la tabla de frecuencias, la vamos a ver en valor absoluto
primer_tri_2019['Country'].value_counts()

Practica 30: Partiendo del dataframe del trimestre, averiguar la tabla de frecuencias por CUSTOMER, de los clientes que son de Brazil, Panama o USA y cuyo nombre de cliente acabe por la letra n

In [ ]:
#Solución practica 30
#Voy a filtrar por Country con isin
filtro = primer_tri_2019['Country'].isin(['Brazil','USA','Panama'])
datos = primer_tri_2019[filtro]
#Voy a reasignar datos para solo los CUSTOMERS que terminan por n
filtro = datos['Customer'].str.endswith('n')
datos = datos[filtro]
#Con los datos filtrados, voy a hacer la tabla de frecuencias
datos['Customer'].value_counts()

In [ ]:
print(datos['Customer'].value_counts())

In [ ]:
#datos = datos['Customer'].value_counts()
#datos.info()

In [ ]:
#Guardar la tabla de frecuencias en un fichero
type(datos['Customer'].value_counts())

In [ ]:
#Como convertimos una agrupación, cuyo indice deberia de ser una columna, en un dataframe, con reset_index() * convertir una serie en un dataframe
datos = datos['Customer'].value_counts().reset_index()
type(datos)

In [ ]:
print(datos)

In [ ]:
#Ya tengo el DataFrame, lo vamos a guardar en un fichero csv. Ojo la ruta entera, incluye carpeta/subcarpeta/nombre fichero/extension y poner la r delante. Un parametro sep= con que caracter queremos separar los datos parametro index=False
datos.to_csv(r'C:\temp\frecuencia_clientes.csv',sep=';',index=False)

In [ ]:
#La tabla de frecuencias con valores absolutos, vamos a ver la tabla de frecuencias con valores relativos en %, con normalize = True
round(primer_tri_2019['Country'].value_counts(normalize=True) * 100, 2)

In [88]:
#Guardar en un csv las frecuencias por Country del dataframe del trimestre, tanto las absolutas como las relativas
#Guardar en un dataframe las absolutas
absolutas = primer_tri_2019['Country'].value_counts().reset_index()
#Guardo en un dataframe las relativas
relativas = round(primer_tri_2019['Country'].value_counts(normalize=True) * 100, 2).reset_index()
#Combinar los 2 dataframes para tener uno solo, eso lo haremos con merge
total_frecuencias = pd.merge(absolutas,relativas,on="Country",how='inner')
total_frecuencias

    Country  count  proportion
0    Panama    153       20.93
1       USA    150       20.52
2    Brazil    146       19.97
3  Colombia    145       19.84
4    Canada    137       18.74

In [87]:
absolutas

    Country  count
0    Panama    153
1       USA    150
2    Brazil    146
3  Colombia    145
4    Canada    137